# Generated by Django 6.1.1 on 2026-09-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricPower_x_Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare_amount_kwh', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='valor da tarifa da energia elétrica')),
                ('date', models.DateField(verbose_name='data referencial')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electric_power_fares', to='store.store', verbose_name='estabelecimento')),
                ('unit', models.ForeignKey(default=10, limit_choices_to={'physical_quantity__slug': 'tarifa-energia'}, on_delete=django.db.models.deletion.PROTECT, to='unit.unit', verbose_name='unidade da tarifa de energia elétrica')),
            ],
            options={
                'verbose_name': 'Tarifa de Energia por Estabelecimento',
                'verbose_name_plural': 'Tarifas de Energia por Estabelecimento',
                'db_table': 'lve_sto_electric_power_x_store',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['store', '-date'], name='lve_sto_ele_store_i_ed68aa_idx'), models.Index(fields=['-date'], name='lve_sto_ele_date_25583a_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'date'), name='unique_fare_per_store_and_date'), models.CheckConstraint(condition=models.Q(('fare_amount_kwh__gte', 0)), name='fare_amount_kwh_non_negative')],
            },
        ),
    ]
