# Generated by Django 6.1.1 on 2026-09-23 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electric_power_x_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='electricpower_x_store',
            new_name='lve_sto_ele_store_i_ed68aa_idx',
            old_name='lve_sto_ele_store_i_2c5788_idx',
        ),
        migrations.RenameIndex(
            model_name='electricpower_x_store',
            new_name='lve_sto_ele_date_25583a_idx',
            old_name='lve_sto_ele_date_1dcb2c_idx',
        ),
        migrations.AlterModelTable(
            name='electricpower_x_store',
            table='lve_sto_electric_power_x_store',
        ),
    ]
