# Generated by Django 6.1.1 on 2026-09-28 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_power_x_store', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricpower_x_store',
            name='unit',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, to='unit.unit', verbose_name='unidade da tarifa de energia elétrica'),
        ),
    ]
