# Generated by Django 6.1.1 on 2026-09-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_power_x_store', '0002_rename_lve_sto_ele_store_i_2c5788_idx_lve_sto_ele_store_i_ed68aa_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricpower_x_store',
            name='fare_amount_kwh',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='valor da tarifa da energia elétrica'),
        ),
    ]
