# Generated by Django 6.1.1 on 2026-09-28 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric_power_x_store', '0003_alter_electricpower_x_store_unit'),
        ('unit', '0002_unit_conversion_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricpower_x_store',
            name='unit',
            field=models.ForeignKey(default=10, limit_choices_to={'physical_quantity__slug': 'tarifa-energia'}, on_delete=django.db.models.deletion.PROTECT, to='unit.unit', verbose_name='unidade da tarifa de energia elétrica'),
        ),
    ]
