# Generated by Django 6.1.1 on 2026-09-24 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unit', '0002_remove_unit_base_factor'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_recipe', models.CharField(max_length=120, verbose_name='receita base')),
                ('description', models.CharField(max_length=600, verbose_name='descrição da receita base')),
                ('size', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='tamanho da receita base')),
                ('unit_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unit.unit', verbose_name='unidade do tamanho da receita base')),
            ],
            options={
                'verbose_name': 'Receita Base',
                'verbose_name_plural': 'Receitas Base',
                'db_table': 'lve_rec_base_recipe',
                'ordering': ['base_recipe', 'size', 'unit_size'],
            },
        ),
    ]
