# Generated by Django 6.1.1 on 2026-09-24 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_store_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=120, verbose_name='produto')),
                ('description_product', models.CharField(max_length=600, verbose_name='descrição do produto')),
                ('name_menu', models.CharField(max_length=48, verbose_name='nome para o menu')),
                ('description_menu', models.CharField(max_length=120, verbose_name='descrição do menu')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.store')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'lve_pro_products',
                'ordering': ['product'],
            },
        ),
    ]
