# Generated by Django 6.1.1 on 2026-09-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_sub_category', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=120, verbose_name='produto')),
                ('description_product', models.CharField(max_length=600, verbose_name='descrição do produto')),
                ('name_menu', models.CharField(max_length=48, verbose_name='nome para o menu')),
                ('description_menu', models.CharField(max_length=120, verbose_name='descrição do menu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.store')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_sub_category.productsubcategory')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'lve_pro_products',
                'ordering': ['product'],
                'constraints': [models.UniqueConstraint(fields=('store', 'product'), name='unique_product_per_store')],
            },
        ),
    ]
