# Generated by Django 6.1.1 on 2026-10-07 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('store', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_weight_or_volume',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True, verbose_name='peso ou volume'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_weight_or_volume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='unit_product', to='unit.unit', verbose_name='unidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_store', to='store.store', verbose_name='Loja'),
        ),
    ]
