# Generated by Django 6.1.1 on 2026-09-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_active_product_created_at_product_updated_at'),
        ('product_sub_category', '0002_productsubcategory_active_and_more'),
        ('store', '0002_alter_store_id_store'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('store', 'product'), name='unique_product_per_store'),
        ),
    ]
