# Generated by Django 6.1.1 on 2026-09-28 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_process_base_recipe', '0001_initial'),
        ('food_ingredient', '0002_alter_foodingredient_table'),
        ('stage_base_recipe', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='executionprocessbaserecipe',
            options={'ordering': ['base_recipe', 'stage_execution', 'operation_execution'], 'verbose_name': 'Execução do Processo da receita base', 'verbose_name_plural': 'Execuções dos Processos da receita base'},
        ),
        migrations.AlterField(
            model_name='executionprocessbaserecipe',
            name='elapsed_time',
            field=models.DurationField(verbose_name='tempo decorrido'),
        ),
        migrations.AlterField(
            model_name='executionprocessbaserecipe',
            name='food_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='food_ingredient.foodingredient', verbose_name='insumo'),
        ),
        migrations.AlterField(
            model_name='executionprocessbaserecipe',
            name='qtde_food_ingredient',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='qtde insumo'),
        ),
        migrations.AlterField(
            model_name='executionprocessbaserecipe',
            name='stage_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stage_base_recipe.stagebaserecipe', verbose_name='etapa da execução do produto'),
        ),
        migrations.AlterField(
            model_name='executionprocessbaserecipe',
            name='unidade_qtde_food_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='unit.unit', verbose_name='unidade da qtde de insumo'),
        ),
    ]
