# Generated by Django 6.1.1 on 2026-09-26 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sub_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterProductionSubProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_production', models.DateTimeField(verbose_name='Data e horário da produção de sub produtos')),
                ('done', models.BooleanField(verbose_name='feito')),
                ('sub_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sub_product.subproduct', verbose_name='sub produto')),
            ],
            options={
                'verbose_name': 'Registro das Produções de Sub produtos',
                'db_table': 'lve_pro_register_production_sub_product',
                'ordering': ['sub_product', 'date_production', 'done'],
            },
        ),
        migrations.CreateModel(
            name='FeedBackProductionSubProdcts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Retorno da Produção de Sub produtos')),
                ('register_production_sub_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='register_production_sub_product.registerproductionsubproducts', verbose_name='Feed Back da Produção de Sub Produtos.')),
            ],
            options={
                'verbose_name': 'FeedBack do registro de Produção',
                'verbose_name_plural': 'FeedBacks dos Registros de Produção',
                'db_table': 'lve_pro_feedback_production_sub_product',
                'ordering': ['register_production_sub_product'],
            },
        ),
    ]
