# Generated by Django 6.1.1 on 2026-09-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_production_sub_product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedBackProductionSubProdcts',
            new_name='FeedBackProductionSubProducts',
        ),
    ]
