# Generated by Django 6.1.1 on 2026-09-28 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_production_sub_product', '0002_rename_feedbackproductionsubprodcts_feedbackproductionsubproducts'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerproductionsubproducts',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10, verbose_name='quantidade produzida'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registerproductionsubproducts',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='unit.unit', verbose_name='unidade da quantidade produzida'),
            preserve_default=False,
        ),
    ]
