# Generated by Django 6.1.1 on 2026-09-28 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_production_sub_product', '0003_registerproductionsubproducts_quantity_and_more'),
        ('store', '0002_alter_store_id_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registerproductionsubproducts',
            options={'ordering': ['store', 'sub_product', 'date_production', 'done'], 'verbose_name': 'Registro da Produção de Sub produto', 'verbose_name_plural': 'Registros das Produções de Sub produtos'},
        ),
        migrations.AddField(
            model_name='registerproductionsubproducts',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store.store', verbose_name='estabelecimento'),
            preserve_default=False,
        ),
    ]
