# Generated by Django 6.1.1 on 2026-09-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_recipe', '0001_initial'),
        ('food_ingredient', '0001_initial'),
        ('operation_base_recipe', '0001_initial'),
        ('stage_base_recipe', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionOperationBaseRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_execution', models.CharField(max_length=240, verbose_name='descrição da execução')),
                ('qtde_food_ingredient', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='qtde insumo')),
                ('unincorporated_ingredient', models.BooleanField(default=False, verbose_name='ingrediente não incorporado no peso total')),
                ('elapsed_time', models.DurationField(verbose_name='tempo decorrido')),
                ('base_recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_recipe.baserecipe', verbose_name='receita base')),
                ('food_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='food_ingredient.foodingredient', verbose_name='insumo')),
                ('operation_execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operation_base_recipe.operationbaserecipe', verbose_name='operação da execução')),
                ('stage_execution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stage_base_recipe.stagebaserecipe', verbose_name='etapa da execução do produto')),
                ('unidade_qtde_food_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='unit.unit', verbose_name='unidade da qtde de insumo')),
            ],
            options={
                'verbose_name': 'Execução da Operação da receita base',
                'verbose_name_plural': 'Execuções das Operações da receita base',
                'db_table': 'lve_rec_execution_operation_base_recipe',
                'ordering': ['base_recipe', 'stage_execution', 'operation_execution'],
            },
        ),
    ]
