# Generated by Django 6.1.1 on 2026-10-03 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution_operation_base_recipe', '0001_initial'),
        ('machinery', '0001_initial'),
        ('operation_base_recipe', '0001_initial'),
        ('stage_base_recipe', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionoperationbaserecipe',
            name='machinery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_machinery', to='machinery.machinery', verbose_name='maquinário'),
        ),
        migrations.AddField(
            model_name='executionoperationbaserecipe',
            name='operation_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operation_base_recipe.operationbaserecipe', verbose_name='operação da execução'),
        ),
        migrations.AddField(
            model_name='executionoperationbaserecipe',
            name='stage_execution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stage_base_recipe.stagebaserecipe', verbose_name='etapa da execução do produto'),
        ),
        migrations.AddField(
            model_name='executionoperationbaserecipe',
            name='unidade_qtde_food_ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='unit.unit', verbose_name='unidade da qtde de insumo'),
        ),
    ]
