# Generated by Django 6.1.1 on 2026-09-29 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_operation_base_recipe', '0001_initial'),
        ('machinery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionoperationbaserecipe',
            name='machinery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_steps', to='machinery.machinery', verbose_name='maquinário'),
        ),
    ]
