# Generated by Django 6.1.1 on 2026-09-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_operation_base_recipe', '0002_executionoperationbaserecipe_machinery'),
        ('machinery', '0002_machinery_code_utensil'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionoperationbaserecipe',
            name='utensils',
            field=models.ManyToManyField(blank=True, related_name='process_steps', to='machinery.utensil', verbose_name='utensílios'),
        ),
    ]
