# Generated by Django 6.1.1 on 2026-10-03 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('execution_operation_base_recipe', '0002_initial'),
        ('utensil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionoperationbaserecipe',
            name='utensils',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='process_utensils', to='utensil.utensil', verbose_name='utensílios'),
        ),
    ]
