# Generated by Django 6.1.1 on 2026-10-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_operation_base_recipe', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionoperationbaserecipe',
            name='execution_time',
            field=models.DurationField(default="00:00", verbose_name='tempo de execução'),
            preserve_default=False,
        ),
    ]
