# Generated by Django 6.1.1 on 2026-10-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_operation_base_recipe', '0004_executionoperationbaserecipe_execution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionoperationbaserecipe',
            name='elapsed_time',
            field=models.DurationField(help_text='tempo em minutos', verbose_name='tempo decorrido'),
        ),
        migrations.AlterField(
            model_name='executionoperationbaserecipe',
            name='execution_time',
            field=models.DurationField(help_text='tempo em minutos', verbose_name='tempo de execução (min)'),
        ),
    ]
