# Generated by Django 6.1.1 on 2026-10-06 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_recipe', '0001_initial'),
        ('execution_operation_base_recipe', '0005_alter_executionoperationbaserecipe_elapsed_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionoperationbaserecipe',
            name='base_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='base_recipe.baserecipe', verbose_name='receita base'),
        ),
    ]
