# Generated by Django 6.1.1 on 2026-10-08 14:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_operation_base_recipe', '0006_alter_executionoperationbaserecipe_base_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='executionoperationbaserecipe',
            name='incorporation_percentage',
        ),
        migrations.AddField(
            model_name='executionoperationbaserecipe',
            name='incorporation_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Quanto do insumo fica no produto final. 100 = tudo incorporado; 0 = nada (ex: água de cozimento descartada); 80 = 20% se perde no processo.', max_digits=5, verbose_name='percentual de incorporação do insumo no produto'),
        ),
    ]
