# Generated by Django 6.1.1 on 2026-10-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_operation_base_recipe', '0007_remove_executionoperationbaserecipe_unincorporated_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executionoperationbaserecipe',
            name='pH',
            field=models.DecimalField(decimal_places=2, default=7.0, max_digits=5, verbose_name='pH'),
        ),
        migrations.AddField(
            model_name='executionoperationbaserecipe',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=20.0, max_digits=5, verbose_name='temperatura'),
        ),
    ]
