# Generated by Django 6.1.1 on 2026-10-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_operation_base_recipe', '0008_executionoperationbaserecipe_ph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executionoperationbaserecipe',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=6, verbose_name='temperatura'),
        ),
    ]
