# Generated by Django 6.1.1 on 2026-09-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterProductionProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_production', models.DateTimeField(verbose_name='Data e horário da produção de sub produtos')),
                ('done', models.BooleanField(verbose_name='feito')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='quantidade produzida')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='produto')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unit.unit', verbose_name='unidade da quantidade produzida')),
            ],
            options={
                'verbose_name': 'Registro das Produções de Produtos',
                'db_table': 'lve_pdc_production_product',
                'ordering': ['product', 'date_production', 'done'],
            },
        ),
        migrations.CreateModel(
            name='FeedBackProductionProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Retorno da Produção de Produtos')),
                ('register_production_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_production.registerproductionproducts', verbose_name='Feed Back da Produção de Produtos.')),
            ],
            options={
                'verbose_name': 'FeedBack do registro de Produção',
                'verbose_name_plural': 'FeedBacks dos Registros de Produção',
                'db_table': 'lve_pdc_feedback_production_product',
                'ordering': ['register_production_product'],
            },
        ),
    ]
