# Generated by Django 6.1.1 on 2026-09-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessBaseRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_base_recipe', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Processo da receita base',
                'verbose_name_plural': 'Processos da receita base',
                'db_table': 'lve_rec_process_base_recipe',
                'ordering': ['process_base_recipe'],
            },
        ),
    ]
