# Generated by Django 6.1.1 on 2026-10-03 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sub_product_production', '0001_initial'),
        ('utensil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtensilScheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_initial', models.DateTimeField(verbose_name='data e horário inicial')),
                ('datetime_finish', models.DateTimeField(verbose_name='data e horário final')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('register_production_sub_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='utensil_schedules', to='sub_product_production.registerproductionsubproducts', verbose_name='execução de produção do sub produto')),
                ('utensil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utensil.utensil', verbose_name='utensílio')),
            ],
            options={
                'verbose_name': 'Agendamento de Utensílio',
                'verbose_name_plural': 'Agendamento de Utensílios',
                'db_table': 'lve_mac_utensil_scheduling',
                'ordering': ['datetime_initial', 'datetime_finish', 'utensil'],
                'constraints': [models.CheckConstraint(condition=models.Q(('datetime_finish__gt', models.F('datetime_initial'))), name='utensil_scheduling_finish_after_start')],
            },
        ),
    ]
