# Generated by Django 6.1.1 on 2026-09-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machinery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machinery', models.CharField(max_length=96, verbose_name='maquinário')),
                ('description', models.CharField(max_length=600, verbose_name='descrição completa')),
                ('qtde_power', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='potência do maquinário')),
                ('value_machinery', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='valor do maquinário')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.store', verbose_name='Loja')),
                ('unit_power', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rel_power', to='unit.unit', verbose_name='unidade de potência')),
            ],
            options={
                'verbose_name': 'Maquinário',
                'verbose_name_plural': 'Maquinários',
                'db_table': 'lve_mac_machinery',
                'ordering': ['machinery'],
                'constraints': [models.UniqueConstraint(fields=('store', 'machinery'), name='unique_machinery_per_store')],
            },
        ),
    ]
