# Generated by Django 6.1.1 on 2026-09-29 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinery',
            name='code',
            field=models.CharField(help_text='Atalho curto para o operador localizar o maquinário. Ex.: FOR-01, MAS-01.', max_length=6, unique=True, verbose_name='código operacional'),
        ),
        migrations.CreateModel(
            name='Utensil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utensil', models.CharField(max_length=96, verbose_name='utensílio')),
                ('code', models.CharField(help_text='Atalho curto para o operador localizar o utensílio. Ex.: ASS-G, CUB-01.', max_length=12, unique=True, verbose_name='código operacional')),
                ('description', models.CharField(max_length=600, verbose_name='descrição completa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Utensílio',
                'verbose_name_plural': 'Utensílios',
                'db_table': 'lve_mac_utensil',
                'ordering': ['utensil'],
                'constraints': [models.UniqueConstraint(fields=('store', 'utensil'), name='unique_utensil_per_store')],
            },
        ),
    ]
