# Generated by Django 6.1.1 on 2026-09-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0001_initial'),
        ('store', '0002_alter_store_id_store'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='machinery',
            constraint=models.UniqueConstraint(fields=('store', 'machinery'), name='unique_machinery_per_store'),
        ),
    ]
