# Generated by Django 6.1.1 on 2026-09-28 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_ingredient', '0002_alter_foodingredient_table'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodIngredientDensity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('density', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='densidade')),
                ('reference_temperature_celsius', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='temperatura de referência (°C)')),
                ('date', models.DateField(verbose_name='data da medição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('food_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='densities', to='food_ingredient.foodingredient', verbose_name='insumo')),
                ('mass_unit', models.ForeignKey(limit_choices_to={'physical_quantity__physical_quantity': 'Massa'}, on_delete=django.db.models.deletion.PROTECT, related_name='densities_as_mass', to='unit.unit', verbose_name='unidade de massa')),
                ('volume_unit', models.ForeignKey(limit_choices_to={'physical_quantity__physical_quantity': 'Volume'}, on_delete=django.db.models.deletion.PROTECT, related_name='densities_as_volume', to='unit.unit', verbose_name='unidade de volume')),
            ],
            options={
                'verbose_name': 'Densidade de Insumo',
                'verbose_name_plural': 'Densidades de Insumos',
                'db_table': 'lve_foo_food_ingredient_density',
                'ordering': ['food_ingredient', '-date'],
                'indexes': [models.Index(fields=['food_ingredient', '-date'], name='lve_foo_foo_food_in_545fe4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('density__gt', 0)), name='food_ingredient_density_positive'), models.UniqueConstraint(fields=('food_ingredient', 'reference_temperature_celsius', 'date'), name='unique_density_per_ingredient_temp_date')],
            },
        ),
    ]
