# Generated by Django 6.1.1 on 2026-09-28 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ingredient_density', '0001_initial'),
        ('unit', '0002_unit_conversion_factor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodingredientdensity',
            name='mass_unit',
            field=models.ForeignKey(limit_choices_to={'physical_quantity__slug': 'massa'}, on_delete=django.db.models.deletion.PROTECT, related_name='densities_as_mass', to='unit.unit', verbose_name='unidade de massa'),
        ),
        migrations.AlterField(
            model_name='foodingredientdensity',
            name='volume_unit',
            field=models.ForeignKey(limit_choices_to={'physical_quantity__slug': 'volume'}, on_delete=django.db.models.deletion.PROTECT, related_name='densities_as_volume', to='unit.unit', verbose_name='unidade de volume'),
        ),
    ]
