# Generated by Django 6.1.1 on 2026-09-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StageBaseRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_base_recipe', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Etapa da receita base',
                'verbose_name_plural': 'Etapas da receita base',
                'db_table': 'lve_rec_stage_base_recipe',
                'ordering': ['stage_base_recipe'],
            },
        ),
    ]
