# Generated by Django 6.1.1 on 2026-09-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
    ]
