# Generated by Django 6.1.1 on 2026-09-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='id_store',
            field=models.IntegerField(unique=True, verbose_name='ID da loja no app principal'),
        ),
    ]
