# Generated by Django 6.1.1 on 2026-10-08 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_ingredient', '0002_rename_supplier_foodingredient_main_supplier'),
        ('sub_product_production', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Opcional. Se não informado, usa o preço da última compra.', max_digits=12, null=True, verbose_name='custo real pago')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_ingredient.foodingredient', verbose_name='insumo')),
                ('register_production_sub_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='sub_product_production.registerproductionsubproducts', verbose_name='registro de produção')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unit.unit', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'Insumo da Produção',
                'verbose_name_plural': 'Insumos da Produção',
                'db_table': 'lve_pdc_production_input',
                'ordering': ['register_production_sub_product', 'food_ingredient'],
                'constraints': [models.UniqueConstraint(fields=('register_production_sub_product', 'food_ingredient'), name='unique_input_per_production_and_ingredient')],
            },
        ),
    ]
