# Generated by Django 6.1.1 on 2026-09-29 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_ingredient', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodIngredientPortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade por unidade')),
                ('date', models.DateField(verbose_name='data da medição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('food_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portions', to='food_ingredient.foodingredient', verbose_name='insumo')),
                ('reference_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portions_as_reference', to='unit.unit', verbose_name='unidade de referência')),
                ('unit', models.ForeignKey(limit_choices_to={'physical_quantity__slug': 'unidade'}, on_delete=django.db.models.deletion.PROTECT, related_name='portions_as_count', to='unit.unit', verbose_name='unidade de contagem')),
            ],
            options={
                'verbose_name': 'Porção de Insumo',
                'verbose_name_plural': 'Porções de Insumos',
                'db_table': 'lve_foo_food_ingredient_portion',
                'ordering': ['food_ingredient', '-date'],
                'indexes': [models.Index(fields=['food_ingredient', '-date'], name='lve_foo_foo_food_in_3ba0fb_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('reference_quantity__gt', 0)), name='food_ingredient_portion_positive'), models.UniqueConstraint(fields=('food_ingredient', 'unit', 'date'), name='unique_portion_per_ingredient_unit_date')],
            },
        ),
    ]
