# Generated by Django 6.1.1 on 2026-09-26 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier_food_ingredients', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_ingredient', models.CharField(max_length=120, verbose_name='insumos')),
                ('description', models.CharField(max_length=600, verbose_name='descrição minuciosa do insumo')),
                ('qtde_default_shopping', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='qtde padrão para compra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplier_food_ingredients.supplierfoodingrdients', verbose_name='Fornecedor de Insumo')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unit.unit', verbose_name='unidade')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'db_table': 'lve_ins_food_ingredients',
                'ordering': ['food_ingredient'],
            },
        ),
    ]
