# Generated by Django 6.1.1 on 2026-09-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodingredient',
            name='active',
            field=models.BooleanField(default=True, verbose_name='ativo'),
        ),
        migrations.AddField(
            model_name='foodingredient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-09-24', verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodingredient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
    ]
