# Generated by Django 6.1.1 on 2026-09-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_ingredient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foodingredient',
            table='lve_foo_food_ingredients',
        ),
    ]
