# Generated by Django 6.1.1 on 2026-10-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_ingredient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodingredient',
            old_name='supplier',
            new_name='main_supplier',
        ),
    ]
