# Generated by Django 6.1.1 on 2026-09-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category', models.CharField(max_length=60, verbose_name='sub categoria do produto')),
                ('description_menu', models.CharField(max_length=120, verbose_name='descrição para o menu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product_category.productcategory', verbose_name='categoria do produto')),
            ],
            options={
                'verbose_name': 'Sub Categoria de Produto',
                'verbose_name_plural': 'Sub Categorias de Produtos',
                'db_table': 'lve_pdv_product_sub_category',
                'ordering': ['sub_category'],
            },
        ),
    ]
