# Generated by Django 6.1.1 on 2026-10-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_sub_category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='markup_default',
            field=models.DecimalField(decimal_places=4, default=200.0, max_digits=8, verbose_name='markup padrão'),
        ),
    ]
