# Generated by Django 6.1.1 on 2026-09-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_product_type', models.CharField(max_length=60, verbose_name='Tipo do sub produto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Sub Produto',
                'verbose_name_plural': 'Tipos de Sub Produtos',
                'db_table': 'lve_pdv_sub_product_type',
                'ordering': ['sub_product_type'],
            },
        ),
    ]
