# Generated by Django 6.1.1 on 2026-09-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_product_type', models.CharField(max_length=60, verbose_name='Sub tipo do sub produto')),
            ],
            options={
                'verbose_name': 'Tipo de Sub Produto',
                'verbose_name_plural': 'Tipos de Sub Produtos',
                'db_table': 'lve_pdv_sub_product_type',
                'ordering': ['sub_product_type'],
            },
        ),
    ]
