# Generated by Django 6.1.1 on 2026-09-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_product_type', '0002_subproducttype_active_subproducttype_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproducttype',
            name='sub_product_type',
            field=models.CharField(max_length=60, verbose_name='Tipo do sub produto'),
        ),
    ]
