# Generated by Django 6.1.1 on 2026-09-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_recipe', '0001_initial'),
        ('sub_product_sub_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_product', models.CharField(max_length=60, verbose_name='Sub Produto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('base_recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_recipe.baserecipe', verbose_name='receita base')),
                ('sub_product_sub_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sub_product_sub_type.subproductsubtype', verbose_name='Sub Tipo do Sub Produto')),
            ],
            options={
                'verbose_name': 'Sub Produto',
                'verbose_name_plural': 'Sub produtos',
                'db_table': 'lve_spr_sub_product',
                'ordering': ['sub_product'],
            },
        ),
    ]
