# Generated by Django 6.1.1 on 2026-09-28 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subproduct',
            options={'ordering': ['sub_product'], 'verbose_name': 'Sub Produto', 'verbose_name_plural': 'Sub produtos'},
        ),
        migrations.AlterModelTable(
            name='subproduct',
            table='lve_spr_sub_product',
        ),
    ]
