# Generated by Django 6.1.1 on 2026-09-23 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageHourlyWage_x_Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_hourly_wage', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='valor médio da hora trabalhada')),
                ('date', models.DateField(verbose_name='data referencial')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='average_hourly_wage', to='store.store', verbose_name='estabelecimento')),
            ],
            options={
                'verbose_name': 'Valor médio da hora trabalhada por Estabelecimento',
                'verbose_name_plural': 'Valor médio da hora trabalhada por Estabelecimento',
                'db_table': 'lve_sto_average_hourly_wage_x_store',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['store', '-date'], name='lve_sto_ave_store_i_0922b0_idx'), models.Index(fields=['-date'], name='lve_sto_ave_date_2e243f_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'date'), name='unique_avr_wage_per_store_and_date'), models.CheckConstraint(condition=models.Q(('average_hourly_wage__gte', 0)), name='average_hourly_wage_non_negative')],
            },
        ),
    ]
