# Generated by Django 6.1.1 on 2026-09-28 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('average_hourly_wage_x_store', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagehourlywage_x_store',
            name='unit',
            field=models.ForeignKey(default=11, limit_choices_to={'physical_quantity_id': 8}, on_delete=django.db.models.deletion.PROTECT, to='unit.unit', verbose_name='unidade da tarifa de energia elétrica'),
        ),
    ]
