# Generated by Django 6.1.1 on 2026-09-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierFoodIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=60, verbose_name='Fornecedor de Insumos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Fornecedor de Insumo',
                'verbose_name_plural': 'Fornecedores de Insumos',
                'db_table': 'lve_ins_fornecedores_insumos',
                'ordering': ['supplier'],
            },
        ),
    ]
