# Generated by Django 6.1.1 on 2026-09-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierFoodIngrdients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=60, verbose_name='Fornecedor de Insumos')),
            ],
            options={
                'verbose_name': 'Fornecedor de Insumo',
                'verbose_name_plural': 'Fornecedores de Insumos',
                'db_table': 'lve_ins_fornecedores_insumos',
                'ordering': ['supplier'],
            },
        ),
    ]
