# Generated by Django 6.1.1 on 2026-09-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_food_ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='supplierfoodingredients',
            table='lve_foo_supplier_food_ingredients',
        ),
    ]
