# Generated by Django 6.1.1 on 2026-09-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sub_product_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProductSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_product_sub_type', models.CharField(max_length=60, verbose_name='Sub tipo do sub produto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sub_product_type.subproducttype')),
            ],
            options={
                'verbose_name': 'Sub Tipo de Sub Produto',
                'verbose_name_plural': 'Sub tipos de Sub Produtos',
                'db_table': 'lve_pdv_sub_product_sub_type',
                'ordering': ['sub_product_sub_type'],
            },
        ),
    ]
