# Generated by Django 6.1.1 on 2026-10-08 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_product_sub_type', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subproductsubtype',
            old_name='type',
            new_name='sub_product_type',
        ),
    ]
