# Generated by Django 6.1.1 on 2026-09-26 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machinery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineryScheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_initial', models.DateTimeField(verbose_name='Data e horário inicial')),
                ('datetime_finish', models.DateTimeField(verbose_name='Data e horário final')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='machinery.machinery', verbose_name='maquinário')),
            ],
            options={
                'verbose_name': 'Agendamento de Maquinário',
                'verbose_name_plural': 'Agendamento de Maquinários',
                'db_table': 'lve_mac_machinery_scheduling',
                'ordering': ['datetime_initial', 'datetime_finish', 'machinery'],
            },
        ),
    ]
