# Generated by Django 6.1.1 on 2026-09-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0001_initial'),
        ('machinery_scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='machineryscheduling',
            constraint=models.CheckConstraint(condition=models.Q(('datetime_finish__gt', models.F('datetime_initial'))), name='machinery_scheduling_finish_after_start'),
        ),
    ]
