# Generated by Django 6.1.1 on 2026-09-28 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery_scheduling', '0002_machineryscheduling_machinery_scheduling_finish_after_start'),
        ('register_production_sub_product', '0003_registerproductionsubproducts_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineryscheduling',
            name='register_production_sub_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machinery_schedules', to='register_production_sub_product.registerproductionsubproducts', verbose_name='execução de produção do sub produto'),
        ),
        migrations.AlterField(
            model_name='machineryscheduling',
            name='datetime_finish',
            field=models.DateTimeField(verbose_name='data e horário final'),
        ),
        migrations.AlterField(
            model_name='machineryscheduling',
            name='datetime_initial',
            field=models.DateTimeField(verbose_name='data e horário inicial'),
        ),
    ]
