# Generated by Django 6.1.1 on 2026-09-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_production', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedBackProductionProdcts',
            new_name='FeedBackProductionProducts',
        ),
    ]
