# Generated by Django 6.1.1 on 2026-09-23 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('physical_quantity', '0002_alter_physicalquantity_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=48, verbose_name='unidade física')),
                ('symbol', models.CharField(max_length=3, verbose_name='símbolo da unidade')),
                ('base_factor', models.DecimalField(decimal_places=9, default=1, max_digits=21, verbose_name='fator de conversão em relação à unidade referencial')),
                ('is_benchmark', models.BooleanField(default=False, verbose_name='a unidade é a referencial')),
                ('physical_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='physical_quantity.physicalquantity', verbose_name='grandeza física')),
            ],
            options={
                'verbose_name': 'Unidade Física',
                'verbose_name_plural': 'Unidades Físicas',
                'db_table': 'lve_uni_unit',
                'ordering': ['physical_quantity', 'unit'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_benchmark', True)), fields=('physical_quantity',), name='unique_benchmark_per_physical_quantity')],
            },
        ),
    ]
