# Generated by Django 6.1.1 on 2026-09-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('physical_quantity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=48, verbose_name='unidade física')),
                ('symbol', models.CharField(max_length=3, verbose_name='símbolo da unidade')),
                ('is_benchmark', models.BooleanField(default=False, verbose_name='a unidade é a referencial')),
                ('conversion_factor', models.DecimalField(decimal_places=10, default=1, help_text='Quantas unidades referenciais (benchmark) equivalem a 1 desta unidade. Ex.: se a benchmark de Massa é o grama, então 1 kg tem fator 1000. A própria unidade benchmark deve ter fator 1.', max_digits=20, verbose_name='fator de conversão para a unidade referencial')),
                ('physical_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='physical_quantity.physicalquantity', verbose_name='grandeza física')),
            ],
            options={
                'verbose_name': 'Unidade Física',
                'verbose_name_plural': 'Unidades Físicas',
                'db_table': 'lve_uni_unit',
                'ordering': ['physical_quantity', 'unit'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_benchmark', True)), fields=('physical_quantity',), name='unique_benchmark_per_physical_quantity'), models.CheckConstraint(condition=models.Q(('is_benchmark', False), models.Q(('conversion_factor', 1), ('is_benchmark', True)), _connector='OR'), name='benchmark_unit_must_have_factor_one')],
            },
        ),
    ]
