# Generated by Django 6.1.1 on 2026-09-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_quantity', '0001_initial'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=10, default=1, help_text='Quantas unidades referenciais (benchmark) equivalem a 1 desta unidade. Ex.: se a benchmark de Massa é o grama, então 1 kg tem fator 1000. A própria unidade benchmark deve ter fator 1.', max_digits=20, verbose_name='fator de conversão para a unidade referencial'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(condition=models.Q(('is_benchmark', False), models.Q(('conversion_factor', 1), ('is_benchmark', True)), _connector='OR'), name='benchmark_unit_must_have_factor_one'),
        ),
    ]
