# Generated by Django 6.1.1 on 2026-09-23 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='base_factor',
        ),
    ]
