# Generated by Django 6.1.1 on 2026-09-29 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_ingredient', '0002_alter_foodingredient_table'),
        ('unit', '0002_unit_conversion_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodIngredientPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data da compra')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade comprada')),
                ('unit_price', models.DecimalField(decimal_places=4, help_text='Preço pago por 1 unidade do insumo, na unidade acima.', max_digits=12, verbose_name='preço por unidade')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='preço total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('food_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='food_ingredient.foodingredient', verbose_name='insumo')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unit.unit', verbose_name='unidade da quantidade')),
            ],
            options={
                'verbose_name': 'Compra de Insumo',
                'verbose_name_plural': 'Compras de Insumos',
                'db_table': 'lve_foo_food_ingredient_purchase',
                'ordering': ['food_ingredient', '-date'],
                'indexes': [models.Index(fields=['food_ingredient', '-date'], name='lve_foo_foo_food_in_2f7227_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_quantity_positive'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='purchase_unit_price_non_negative'), models.CheckConstraint(condition=models.Q(('total_price__gte', 0)), name='purchase_total_price_non_negative')],
            },
        ),
    ]
