# Generated by Django 6.1.1 on 2026-10-02 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ingredient_purchase', '0001_initial'),
        ('nf_purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodingredientpurchase',
            name='nf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nf_purchase.nfpurchase', verbose_name='nf'),
        ),
    ]
