# Generated by Django 6.1.1 on 2026-09-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ingredient_purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='foodingredientpurchase',
            name='purchase_unit_price_non_negative',
        ),
        migrations.AlterField(
            model_name='foodingredientpurchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor total pago'),
        ),
        migrations.RemoveField(
            model_name='foodingredientpurchase',
            name='unit_price',
        ),
    ]
