# Generated by Django 6.1.1 on 2026-10-02 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_ingredient_purchase', '0002_foodingredientpurchase_nf'),
        ('nf_purchase', '0004_alter_nfpurchase_options_nfpurchase_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodingredientpurchase',
            name='nf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='nf_purchase.nfpurchase', verbose_name='nf'),
        ),
    ]
