# Generated by Django 6.1.1 on 2026-09-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_quantity', models.CharField(max_length=48, verbose_name='grandeza física')),
                ('slug', models.SlugField(help_text='Identificador estável usado no código. Ex.: massa, volume, temperatura. Não editar depois de definido.', max_length=48, unique=True, verbose_name='identificador canônico')),
            ],
            options={
                'verbose_name': 'Grandeza Física',
                'verbose_name_plural': 'Grandezas Físicas',
                'db_table': 'lve_uni_physical_quantity',
                'ordering': ['physical_quantity'],
            },
        ),
    ]
