# Generated by Django 6.1.1 on 2026-09-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('physical_quantity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physicalquantity',
            options={'ordering': ['physical_quantity'], 'verbose_name': 'Grandeza Física', 'verbose_name_plural': 'Grandezas Físicas'},
        ),
    ]
