# Generated by Django 6.1.1 on 2026-09-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_quantity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalquantity',
            name='slug',
            field=models.SlugField(blank=True, help_text='Identificador estável usado no código. Ex.: massa, volume, temperatura. Não editar depois de definido.', max_length=48, null=True, verbose_name='identificador canônico'),
        ),
    ]
