# Generated by Django 6.1.1 on 2026-09-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_quantity', '0002_physicalquantity_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalquantity',
            name='slug',
            field=models.SlugField(help_text='Identificador estável usado no código. Ex.: massa, volume, temperatura. Não editar depois de definido.', max_length=48, unique=True, verbose_name='identificador canônico'),
        ),
    ]
