# Generated by Django 6.1.1 on 2026-10-02 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier_food_ingredients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data da NF')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier_food_ingredients.supplierfoodingredients', verbose_name='Fornecedor')),
            ],
            options={
                'db_table': 'lve_foo_nf',
            },
        ),
    ]
