# Generated by Django 6.1.1 on 2026-10-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_purchase', '0002_nfpurchase_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfpurchase',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='total da NF'),
        ),
    ]
