# Generated by Django 6.1.1 on 2026-10-02 16:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_purchase', '0003_alter_nfpurchase_total_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nfpurchase',
            options={'ordering': ['-date'], 'verbose_name': 'Nota Fiscal', 'verbose_name_plural': 'Notas Fiscais'},
        ),
        migrations.AddField(
            model_name='nfpurchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nfpurchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em'),
        ),
    ]
