# Generated by Django 6.1.1 on 2026-09-29 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('sub_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_x_Sub_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakers_percentage', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='percentual do padeiro')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Produto')),
                ('sub_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sub_product.subproduct', verbose_name='Sub Produto')),
            ],
            options={
                'verbose_name': 'Produto X Sub-Produto',
                'verbose_name_plural': 'Produtos X Sub-Produtos',
                'db_table': 'lve_pro_product_x_sub_product',
                'ordering': ['product', 'sub_product', 'bakers_percentage'],
            },
        ),
    ]
