# Generated by Django 6.1.1 on 2026-10-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_x_sub_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_x_sub_product',
            name='bakers_percentage',
            field=models.DecimalField(decimal_places=6, max_digits=10, verbose_name='percentual do padeiro'),
        ),
    ]
