# Generated by Django 6.1.1 on 2026-09-28 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_x_sub_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_x_sub_product',
            options={'ordering': ['product', 'sub_product', 'bakers_percentage'], 'verbose_name': 'Produto X Sub-Produto', 'verbose_name_plural': 'Produtos X Sub-Produtos'},
        ),
        migrations.AlterModelTable(
            name='product_x_sub_product',
            table='lve_pro_product_x_sub_product',
        ),
    ]
