# Generated by Django 6.1.1 on 2026-10-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_x_sub_product', '0002_alter_product_x_sub_product_bakers_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_x_sub_product',
            options={'ordering': ['product', 'sub_product', 'composition_percentage'], 'verbose_name': 'Produto X Sub-Produto', 'verbose_name_plural': 'Produtos X Sub-Produtos'},
        ),
        migrations.RenameField(
            model_name='product_x_sub_product',
            old_name='bakers_percentage',
            new_name='composition_percentage',
        ),
    ]
