# Generated by Django 6.1.1 on 2026-10-09 21:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_x_sub_product', '0003_alter_product_x_sub_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_x_sub_product',
            name='after_to',
            field=models.BooleanField(default=False, verbose_name='referência é depois do fim do sub-produto'),
        ),
        migrations.AddField(
            model_name='product_x_sub_product',
            name='at_finish',
            field=models.BooleanField(default=False, verbose_name='referência é o fim do sub-produto'),
        ),
        migrations.AddField(
            model_name='product_x_sub_product',
            name='at_start',
            field=models.BooleanField(default=False, verbose_name='referência é o início do sub-produto'),
        ),
        migrations.AddField(
            model_name='product_x_sub_product',
            name='elapsed_signal',
            field=models.CharField(choices=[('+', 'Somar'), ('-', 'Subtrair')], default='+', max_length=1, verbose_name='sinal do tempo decorrido'),
        ),
        migrations.AddField(
            model_name='product_x_sub_product',
            name='elapsed_time',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Tempo somado ou subtraído do ponto de referência.', verbose_name='tempo decorrido'),
        ),
        migrations.AddField(
            model_name='product_x_sub_product',
            name='relative_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatives', to='product_x_sub_product.product_x_sub_product', verbose_name='sub-produto de referência'),
        ),
    ]
